### ISSUE TITLE
Syck has been removed

### ISSUE THREAD

**Issue by tylercollier** [mislav/choices#8]
Choices is great! Thanks for it!

I'm using Rails 4.0.0.rc1 and Ruby 2.0.0.

When choices is loaded, I'm notified, twice, that "syck has been removed". My research shows that it indeed has. I never noticed that Psych was broken in 1.9.2, but it seems to be working in 2.0.0. Can the code be updated to intelligently check for the Ruby version and not try to load syck in Ruby 2.0?

**Comment by mislav** [comment]
Fixed by #9, thanks!

**Comment by tylercollier** [comment]
Thanks @mislav and @remiprev.
